### PR TITLE
add search product by sku on POS

### PR DESCRIPTION
**Pull request by willbackslash**
This PR adds the functionality of searching the products by name as well for sku in the POS search, and also fixes the search to only filter the matched products on the db

Screenshot:

image

Note: I like your project and I would like to contribute to make a great POS on django

### CODE REVIEW

**Comment by willbackslash** [comment]
@otuoma please check it when you have some free time

**Comment by otuoma** [comment]
I will do some testing and get back @willbackslash - thank you.

**Comment by otuoma** [comment]
The initial vision I had was to do a web app complete with an API to allow it to work with desktop and mobile apps in future, maybe that will still happen.

**Comment by willbackslash** [comment]
> The initial vision I had was to do a web app complete with an API to allow it to work with desktop and mobile apps in future, maybe that will still happen.

Yes, if you want we can migrate it to `django-rest-framework` and I have some experience with `react`, if you want we can
 also create a web client for the API on `react`, let me know what do you think about it

**Pull request closed without merging**
